databases:
  - name: stream-app
    plan: free
    databaseName: stream_db_pgsi
    user: stream_db_pgsi_user

services:
  - type: web
    plan: free
    name: stream-app-api
    runtime: python
  buildCommand: './build.sh'
  startCommand: 'gunicorn stream.asgi:application -k uvicorn.workers.UvicornWorker -w $WEB_CONCURRENCY -b 0.0.0.0:$PORT --timeout 120 --access-logfile -'
  envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stream-app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""
